(println "Hello, World!")
(println "こんにちは / ｺﾝﾆﾁﾊ (Japanese (日本語))")
(println "Здра́вствуйте! (Russian (русский))"
(println "Print Test")
(println 42)
(println 42.42)
(println #x42)
(println '(1 . 2))
(println '(1 2 . nil))
(println nil)
(if (int? 12)
    (println "(int? 12); Pass")
    (println "(int? 12); Fail"))
(if (int? 12.9)
    (println "(int? 12.9); Pass")
    (println "(int? 12.9); Fail")
