;;perhaps rename to unicode-print-test.lisp
(println "LANGUAGE (NATIVE NAME)	HELLO")
(println "----------------------	-----")
(println "ሠላም (Amharic (አማርኛ))")
(println "السّلام عليكم (Arabic ‏(العربيّة))")
(println "নমস্কার (Bengali (বাংলা))")
(println "⠓⠑⠇⠇⠕ (Braille)")
(println "မင်္ဂလာပါ (Burmese (မြန်မာ))")
(println "printf (\"Hello, world!\n\"); (C)")
(println "Dobrý den (Czech (čeština))")
(println "Hej / Goddag / Halløj (Danish (dansk))")
(println "Hallo / Dag (Dutch (Nederlands))")
(println "emacs --no-splash -f view-hello-file (Emacs)")
(println "Hello (English /ˈɪŋɡlɪʃ/)")
(println "Saluton (Eĥoŝanĝo ĉiuĵaŭde) (Esperanto)")
(println "Tere päevast / Tere õhtust (Estonian (eesti keel))")
(println "Hei / Hyvää päivää (Finnish (suomi))")
(println "Bonjour / Salut (French (français))")
(println "გამარჯობა (Georgian (ქართველი))")
(println "Guten Tag / Grüß Gott (German (Deutsch))")
(println "Γειά σας (Greek (ελληνικά))")
(println "Οὖλέ τε καὶ μέγα χαῖρε (Greek, ancient (ἑλληνική))")
(println "નમસ્તે (Gujarati (ગુજરાતી))")
(println "שלום (Hebrew ‏(עברית))")
(println "Szép jó napot! (Hungarian (magyar))")
(println "नमस्ते / नमस्कार । (Hindi (हिंदी))")
(println "Ciao / Buon giorno (Italian (italiano))")
(println "System.out.println(\"Sugeng siang!\"); (Javanese (Jawa))")
(println "ನಮಸ್ಕಾರ (Kannada (ಕನ್ನಡ))")
(println "ជំរាបសួរ (Khmer (ភាសាខ្មែរ))")
(println "ສະບາຍດີ / ຂໍໃຫ້ໂຊກດີ (Lao (ພາສາລາວ))")
(println "നമസ്കാരം (Malayalam (മലയാളം))")
(println "Bonġu / Saħħa (Maltese (il-Malti))")
(println "∀ p ∈ world • hello p  □ (Mathematics)")
(println "Hei / God dag (Norwegian (norsk))")
(println "ଶୁଣିବେ (Oriya (ଓଡ଼ିଆ))")
(println "Dzień dobry! / Cześć! (Polish  (język polski))")
(println "Здра́вствуйте! (Russian (русский))")
(println "ආයුබෝවන් (Sinhala (සිංහල))")
(println "Dobrý deň (Slovak (slovenčina))")
(println "Pozdravljeni! (Slovenian (slovenščina))")
(println "¡Hola! (Spanish (español))")
(println "Hej / Goddag / Hallå (Swedish (svenska))")
(println "வணக்கம் (Tamil (தமிழ்))")
(println "నమస్కారం (Telugu (తెలుగు))")
(println "สวัสดีครับ / สวัสดีค่ะ (Thai (ภาษาไทย))")
(println "བཀྲ་ཤིས་བདེ་ལེགས༎ (Tibetan (བོད་སྐད་))")
(println "ሰላማት (Tigrigna (ትግርኛ))")
(println "Merhaba (Turkish (Türkçe))")
(println "Вітаю (Ukrainian (українська))")
(println "Chào bạn (Vietnamese (tiếng Việt))")
(println "こんにちは / ｺﾝﾆﾁﾊ (Japanese (日本語))")
(println "你好 (Chinese (中文,普通话,汉语))")
(println "早晨, 你好 (Cantonese (粵語,廣東話))")
(println "안녕하세요 / 안녕하십니까 (Korean (한글))")

