/* This file is automatically generated, do not edit*/
#define MAKE_SYMBOL(cname,lname,sym_len,sym_hashv,sym_val,proplist,const_sym) \
  symbol_name cname##_name={.hashv=sym_hashv,.is_const=const_sym,       \
                            .name_len=sym_len,.name=lname};             \
  symbol cname##_val={.val=val,.name=&cname##_name,                 \
                          .plist=proplist,.next=NULL};           
#define MAKE_SELF_QUOTING_SYMBOL(cname,lname,sym_len,sym_hashv,proplist) \
  symbol_name cname##_name={.hashv=sym_hashv,.is_const=1,               \
                                   .name_len=sym_len,.name=lname};      \
  symbol cname##_val={.name=&cname##_name,                              \
                      .plist=proplist,.next=NULL};                      \
  cname##_val.val=symref_sexp(&cname##_val)
#define DEFTYPE(_name_,mval)                                            \
  static const sexp Q##_name_ = {.tag=_type,.val={.meta = mval}};
#define MAKE_TYPE(cname,lname,sym_len,sym_hashv,proplist,type_tag)      \
  symbol_name cname##_name={.hashv=sym_hashv,.is_const=1,               \
                            .name_len=sym_len,.name=lname};             \
  symbol cname##_val={.name=&cname##_name,.plist=proplist,.next=NULL};  \
  cname##_val.val={.tag=sexp_type,.val={.type=type_tag}}
#define DEFUN(cname,numargs)                     \
  sexp cname DEFUN_ARGS_##numargs ;              \
  extern function cname ## _fun
#define DEFUN_ARGS_0	(void)
#define DEFUN_ARGS_1	(sexp)
#define DEFUN_ARGS_2	(sexp, sexp)
#define DEFUN_ARGS_3	(sexp, sexp, sexp)
#define DEFUN_ARGS_4	(sexp, sexp, sexp, sexp)
#define DEFUN_ARGS_5	(sexp, sexp, sexp, sexp,        \
                         sexp)
#define DEFUN_ARGS_6	(sexp, sexp, sexp, sexp,        \
                         sexp, sexp)
#define DEFUN_ARGS_7	(sexp, sexp, sexp, sexp,        \
                         sexp, sexp, sexp)
#define DEFUN_ARGS_8	(sexp, sexp, sexp, sexp,        \
                         sexp, sexp, sexp, sexp)
#define DEFUN_ARGS_MANY (uint64_t,sexp*)
#define DEFUN_ARGS_UNEVALED (sexp)
static void* GC_REALLOC_3(void* ptr,size_t old,size_t new){
  return GC_REALLOC(ptr,new);
}
static void GC_FREE_2(void* ptr,size_t size){
  return GC_FREE(ptr);
}
static void* GC_MALLOC_1(size_t size){
  return GC_MALLOC(size);
}
extern const sexp lisp_pi;
extern const sexp lisp_euler;
extern const sexp lisp_max_long;
extern const sexp lisp_mach_eps;
extern symref lisp_ans_ptr;
extern sexp typeOfTag(_tag tag);
extern sexp typeOf(sexp obj);
void initPrims();
