#line 2 "read.c"

#line 4 "read.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 41
#define YY_END_OF_BUFFER 42
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[171] =
    {   0,
        0,    0,    0,    0,   42,    9,   38,   38,   40,   19,
       36,   23,   24,    9,   37,   33,    1,    1,   34,   39,
        9,   35,   25,   40,   28,   18,    9,   31,   40,   32,
       40,   40,   40,   40,   16,   41,   41,    9,    0,    0,
        0,    0,    0,   38,    0,    7,    0,    0,    0,    0,
        0,    0,   21,   20,   14,    1,    1,    3,    1,    9,
        9,   10,    0,    0,    0,    0,    0,   39,    8,    8,
        8,    0,    0,    0,    0,   26,   27,   29,    9,   15,
       30,    0,    0,   16,   17,   11,    0,    0,    0,    0,
        0,    5,    0,    5,    0,    6,    0,    6,    0,    0,

       22,    0,    0,    0,    0,    3,    0,    9,    4,    2,
       13,    0,    0,    0,    0,    0,    0,    8,    9,    9,
        9,    0,    0,    9,    0,   12,    0,    0,    0,    0,
        0,    0,    6,    0,    0,    0,    0,    4,    0,    0,
        0,    8,    8,    8,    0,    9,    0,    0,    0,    0,
        0,    8,    8,    8,    9,    0,    8,    8,    9,    8,
        8,    9,    8,    9,    8,    9,    8,    9,    8,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    7,
        8,    1,    9,   10,    9,   11,    1,   12,   13,   13,
       13,   13,   13,   13,   14,   13,   13,   15,   16,   17,
       17,   17,   18,   19,   20,   20,   20,   20,   21,   20,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   22,   17,   17,   23,   17,   17,
       24,   25,   26,   27,   17,   28,   29,   20,   20,   20,

       30,   31,   17,   17,   32,   17,   17,   17,   17,   33,
       34,   17,   35,   17,   36,   37,   38,   17,   17,   39,
       17,   17,   40,   41,   42,   17,   17,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   44,   44,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   47,
       47,   47,   47,   47,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44
    } ;

static yyconst flex_int32_t yy_meta[48] =
    {   0,
        1,    2,    3,    4,    5,    2,    2,    2,    1,    2,
        6,    1,    7,    1,    8,    9,    7,    7,    9,    7,
        7,    7,    7,   10,    1,    9,   11,    9,    7,    7,
        1,    7,    7,    7,    7,    7,    7,    7,    1,    9,
       12,   10,    9,    9,    7,    7,    7
    } ;

static yyconst flex_int16_t yy_base[182] =
    {   0,
        0,    0,   43,   44,  448,   35,   49,   51,   85,   42,
      961,  961,  961,  121,  961,  961,  158,   32,  113,    0,
      197,  961,   34,  243,  414,  961,  127,  961,   51,  961,
      961,  391,  381,  372,    0,  372,  406,   49,  131,    0,
      363,  359,  348,   62,  377,  125,  287,  368,  327,  325,
      324,  128,  961,  961,  961,    0,  122,  243,  124,  171,
      315,  257,  233,  345,  322,  317,  315,    0,   54,  961,
      294,  341,  314,  311,  300,  961,  961,  961,  294,  961,
      961,  299,  295,    0,  961,  337,  275,  388,  294,  291,
      282,  139,  236,  256,  310,  961,  309,  307,  266,  234,

      285,  431,  227,  225,  223,  303,  177,  180,  262,    0,
      372,  474,  222,  220,  209,  203,  198,  363,  507,  527,
      547,  153,  152,  387,  144,  380,  577,  139,  119,  114,
      112,  111,    0,  109,  108,  106,  396,  408,  105,  101,
       94,  610,  630,  650,   35,  431,   33,   31,   29,   27,
       26,  670,  690,  439,  448,   16,  710,  730,  453,  750,
      456,  474,  770,  492,  790,  482,  810,  497,  510,  961,
      841,  853,  864,  875,  887,  898,  910,  921,  927,  938,
      949
    } ;

static yyconst flex_int16_t yy_def[182] =
    {   0,
      170,    1,  171,  171,  170,  172,  170,  170,  170,  170,
      170,  170,  170,  172,  170,  170,   14,   17,  173,  174,
      170,  170,  170,  172,  170,  170,   14,  170,  170,  170,
      170,  170,  170,  170,  175,  176,  170,   14,  177,   24,
      170,  170,  170,  170,    9,  178,    9,   47,  170,  170,
      170,  179,  170,  170,  170,   17,   17,  170,   17,   14,
       14,  173,  180,  173,  170,  170,  170,  174,   14,  170,
      177,   24,  170,  170,  170,  170,  170,  170,   14,  170,
      170,  170,  170,  175,  170,  177,  181,  177,  170,  170,
      170,  178,  178,  178,  170,  170,   47,    9,  170,  170,

      179,  179,  170,  170,  170,  170,  170,   14,   14,   61,
      180,  180,  170,  170,  170,  170,  170,   14,   14,   14,
       14,  170,  170,   14,  170,  181,  181,  170,  170,  170,
      170,  170,   47,  170,  170,  170,  170,  170,  170,  170,
      170,   14,   14,   14,  170,   14,  170,  170,  170,  170,
      170,   14,   14,   14,   14,  170,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,    0,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170
    } ;

static yyconst flex_int16_t yy_nxt[1009] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   18,   19,   20,    6,   21,   22,    6,
        6,    6,    6,   23,   24,   25,    6,   26,    6,    6,
        6,    6,    6,    6,   27,    6,    6,    6,    6,   28,
       29,   30,   31,   31,   32,   33,   34,   36,   36,   39,
       44,   44,   44,   44,   38,   80,   52,   76,  126,   40,
       38,   38,   38,   44,   44,   38,   38,   38,  111,  101,
       38,   86,   53,  156,   77,  126,   81,   69,   54,   41,
       42,   43,   55,   37,   37,   45,   45,   45,   46,   45,
       45,   45,   45,   45,   45,   45,   45,   47,   45,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   48,
       47,   47,   47,   47,   47,   45,   47,   47,   47,   47,
       47,   47,   47,   45,   47,   47,   47,   63,   94,   49,
       50,   51,   56,   57,   57,   39,   62,   64,   38,   38,
       38,   87,   94,  151,   38,   40,   38,  111,  150,   95,
      101,   47,  102,  149,   86,   88,  148,   65,   66,   67,
       38,  147,   38,   95,   79,   41,   42,   43,   58,   59,
       59,   59,  103,  104,  105,   89,   90,   91,   60,  108,
       61,  126,  109,  109,  109,  137,   38,   60,  138,  138,
      138,  109,  109,  109,  145,   69,   61,   69,   70,   70,

       70,   70,   70,   70,   70,   69,   70,   70,   69,   69,
       69,   71,   70,   69,   38,   70,   69,   69,   69,   69,
       70,   72,   70,   69,   70,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   70,   70,   70,   94,
      141,   73,   74,   75,   38,   62,   38,   38,   38,   38,
       38,  140,   38,   38,  106,  106,  106,  112,   38,   94,
       95,   38,  139,  107,  111,  136,   38,  135,   38,  101,
       38,  170,  107,  109,  109,  109,  134,  113,  114,  115,
       95,   64,   38,   38,   38,   38,   38,   47,   47,   47,
       96,   47,   47,   47,   47,   47,   47,   47,   47,  127,

       47,   65,   66,   67,   87,   38,   38,   38,   47,  102,
       92,   97,  133,   93,  106,  106,  106,   47,   88,  128,
      129,  130,  124,  107,  132,   47,  110,  110,  110,  103,
      104,  105,  107,  131,  110,  110,   86,  125,   89,   90,
       91,   38,  123,  110,  110,  110,   62,  170,   62,   62,
       62,   62,   62,  122,   62,   62,   69,  117,  118,  116,
       62,   88,  119,   62,   62,  118,  100,   99,   62,   47,
       62,   98,   62,  118,   38,   38,   38,  118,  120,  121,
       92,   89,   90,   91,   62,   62,   62,   62,   62,   86,
       83,   86,   86,   86,   86,   86,  112,   86,   38,   38,

       38,   82,   86,   86,  127,   38,   86,  138,  138,  138,
       80,   86,   55,   86,   83,   86,  113,  114,  115,  138,
      138,  138,  146,   82,  128,  129,  130,   86,   86,   86,
       86,   86,  101,   38,  101,  101,  101,  101,  101,   78,
      101,  101,   38,   38,   38,  101,  101,  170,  170,  101,
       38,   38,   38,  170,  101,  170,  101,  170,  101,   38,
       38,   38,  155,  170,   38,   38,   38,   38,   38,   38,
      101,  101,  101,  101,  101,  111,  170,  111,  111,  111,
      111,  111,  159,  111,  111,   38,   38,   38,  111,  111,
      162,  170,  111,   38,   38,   38,  170,  111,  170,  111,

      170,  111,  170,   38,   38,   38,  170,  164,   38,   38,
       38,  168,  170,  111,  111,  111,  111,  111,  142,  142,
      142,   38,   38,   38,  170,  170,  142,  142,  166,  170,
      170,  170,  170,  170,  170,  142,  142,  142,  143,  143,
      143,  170,  170,  170,  170,  170,  143,  143,  170,  170,
      170,  170,  170,  170,  170,  143,  143,  143,  144,  144,
      144,  170,  170,  170,  170,  170,  144,  144,  170,  170,
      170,  170,  170,  170,  170,  144,  144,  144,  126,  170,
      126,  126,  126,  126,  126,  170,  126,  126,  170,  170,
      170,  126,  126,  170,  170,  126,  170,  170,  170,  170,

      126,  170,  126,  170,  126,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  126,  126,  126,  126,
      126,  152,  152,  152,  170,  170,  170,  170,  170,  152,
      152,  170,  170,  170,  170,  170,  170,  170,  152,  152,
      152,  153,  153,  153,  170,  170,  170,  170,  170,  153,
      153,  170,  170,  170,  170,  170,  170,  170,  153,  153,
      153,  154,  154,  154,  170,  170,  170,  170,  170,  154,
      154,  170,  170,  170,  170,  170,  170,  170,  154,  154,
      154,  157,  157,  157,  170,  170,  170,  170,  170,  157,
      157,  170,  170,  170,  170,  170,  170,  170,  157,  157,

      157,  158,  158,  158,  170,  170,  170,  170,  170,  158,
      158,  170,  170,  170,  170,  170,  170,  170,  158,  158,
      158,  160,  160,  160,  170,  170,  170,  170,  170,  160,
      160,  170,  170,  170,  170,  170,  170,  170,  160,  160,
      160,  161,  161,  161,  170,  170,  170,  170,  170,  161,
      161,  170,  170,  170,  170,  170,  170,  170,  161,  161,
      161,  163,  163,  163,  170,  170,  170,  170,  170,  163,
      163,  170,  170,  170,  170,  170,  170,  170,  163,  163,
      163,  165,  165,  165,  170,  170,  170,  170,  170,  165,
      165,  170,  170,  170,  170,  170,  170,  170,  165,  165,

      165,  167,  167,  167,  170,  170,  170,  170,  170,  167,
      167,  170,  170,  170,  170,  170,  170,  170,  167,  167,
      167,  169,  169,  169,  170,  170,  170,  170,  170,  169,
      169,  170,  170,  170,  170,  170,  170,  170,  169,  169,
      169,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   38,  170,  170,  170,  170,  170,   38,
       38,  170,  170,   38,   62,  170,  170,  170,  170,  170,
       62,   62,  170,  170,   62,   68,   68,  170,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   84,   84,   84,
       84,  170,   84,   84,   84,   84,   84,   84,   85,   85,

       85,  170,  170,   85,   85,   85,   85,  170,  170,   85,
       86,  170,  170,  170,  170,   86,   86,  170,  170,  170,
       86,   93,   93,   93,   93,   93,   93,  101,  170,  170,
      170,  170,  170,  101,  170,  170,  170,  101,  111,  170,
      170,  170,  170,  170,  111,  170,  170,  170,  111,  126,
      170,  170,  170,  170,  170,  126,  170,  170,  170,  126,
        5,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,

      170,  170,  170,  170,  170,  170,  170,  170
    } ;

static yyconst flex_int16_t yy_chk[1009] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    6,
        7,    7,    8,    8,   18,   29,   10,   23,  156,    6,
       38,   38,   38,   44,   44,   69,   69,   69,  151,  150,
       18,  149,   10,  148,   23,  147,   29,  145,   10,    6,
        6,    6,   10,    3,    4,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   19,   46,    9,
        9,    9,   14,   14,   14,   14,  141,   19,   27,   27,
       27,   39,   92,  140,   57,   14,   59,  139,  136,   46,
      135,  134,   52,  132,  131,   39,  130,   19,   19,   19,
       57,  129,   59,   92,   27,   14,   14,   14,   17,   17,
       17,   17,   52,   52,   52,   39,   39,   39,   17,   60,
       17,  128,   60,   60,   60,  107,  125,   17,  107,  107,
      107,  108,  108,  108,  123,  122,   17,   21,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   93,
      117,   21,   21,   21,   24,  116,   24,   24,   24,   24,
       24,  115,   24,   24,   58,   58,   58,   63,   24,   94,
       93,   24,  114,   58,  113,  105,   24,  104,   24,  103,
       24,   62,   58,  109,  109,  109,  100,   63,   63,   63,
       94,   62,   24,   24,   24,   24,   24,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   87,

       47,   62,   62,   62,   71,   79,   79,   79,   99,  101,
       98,   47,   97,   95,  106,  106,  106,   47,   71,   87,
       87,   87,   79,  106,   91,   47,   61,   61,   61,  101,
      101,  101,  106,   90,   61,   61,   89,   83,   71,   71,
       71,   82,   75,   61,   61,   61,   64,   86,   64,   64,
       64,   64,   64,   74,   64,   64,   73,   67,   72,   66,
       64,   86,   72,   64,   65,   72,   51,   50,   64,   49,
       64,   48,   64,   72,  118,  118,  118,   72,   72,   72,
       45,   86,   86,   86,   64,   64,   64,   64,   64,   88,
       43,   88,   88,   88,   88,   88,  111,   88,  124,  124,

      124,   42,   88,   88,  126,   41,   88,  137,  137,  137,
       37,   88,   36,   88,   34,   88,  111,  111,  111,  138,
      138,  138,  124,   33,  126,  126,  126,   88,   88,   88,
       88,   88,  102,   32,  102,  102,  102,  102,  102,   25,
      102,  102,  146,  146,  146,  102,  102,    5,    0,  102,
      154,  154,  154,    0,  102,    0,  102,    0,  102,  155,
      155,  155,  146,    0,  159,  159,  159,  161,  161,  161,
      102,  102,  102,  102,  102,  112,    0,  112,  112,  112,
      112,  112,  155,  112,  112,  162,  162,  162,  112,  112,
      159,    0,  112,  166,  166,  166,    0,  112,    0,  112,

        0,  112,    0,  164,  164,  164,    0,  162,  168,  168,
      168,  166,    0,  112,  112,  112,  112,  112,  119,  119,
      119,  169,  169,  169,    0,    0,  119,  119,  164,    0,
        0,    0,    0,    0,    0,  119,  119,  119,  120,  120,
      120,    0,    0,    0,    0,    0,  120,  120,    0,    0,
        0,    0,    0,    0,    0,  120,  120,  120,  121,  121,
      121,    0,    0,    0,    0,    0,  121,  121,    0,    0,
        0,    0,    0,    0,    0,  121,  121,  121,  127,    0,
      127,  127,  127,  127,  127,    0,  127,  127,    0,    0,
        0,  127,  127,    0,    0,  127,    0,    0,    0,    0,

      127,    0,  127,    0,  127,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  127,  127,  127,  127,
      127,  142,  142,  142,    0,    0,    0,    0,    0,  142,
      142,    0,    0,    0,    0,    0,    0,    0,  142,  142,
      142,  143,  143,  143,    0,    0,    0,    0,    0,  143,
      143,    0,    0,    0,    0,    0,    0,    0,  143,  143,
      143,  144,  144,  144,    0,    0,    0,    0,    0,  144,
      144,    0,    0,    0,    0,    0,    0,    0,  144,  144,
      144,  152,  152,  152,    0,    0,    0,    0,    0,  152,
      152,    0,    0,    0,    0,    0,    0,    0,  152,  152,

      152,  153,  153,  153,    0,    0,    0,    0,    0,  153,
      153,    0,    0,    0,    0,    0,    0,    0,  153,  153,
      153,  157,  157,  157,    0,    0,    0,    0,    0,  157,
      157,    0,    0,    0,    0,    0,    0,    0,  157,  157,
      157,  158,  158,  158,    0,    0,    0,    0,    0,  158,
      158,    0,    0,    0,    0,    0,    0,    0,  158,  158,
      158,  160,  160,  160,    0,    0,    0,    0,    0,  160,
      160,    0,    0,    0,    0,    0,    0,    0,  160,  160,
      160,  163,  163,  163,    0,    0,    0,    0,    0,  163,
      163,    0,    0,    0,    0,    0,    0,    0,  163,  163,

      163,  165,  165,  165,    0,    0,    0,    0,    0,  165,
      165,    0,    0,    0,    0,    0,    0,    0,  165,  165,
      165,  167,  167,  167,    0,    0,    0,    0,    0,  167,
      167,    0,    0,    0,    0,    0,    0,    0,  167,  167,
      167,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  172,    0,    0,    0,    0,    0,  172,
      172,    0,    0,  172,  173,    0,    0,    0,    0,    0,
      173,  173,    0,    0,  173,  174,  174,    0,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  175,  175,  175,
      175,    0,  175,  175,  175,  175,  175,  175,  176,  176,

      176,    0,    0,  176,  176,  176,  176,    0,    0,  176,
      177,    0,    0,    0,    0,  177,  177,    0,    0,    0,
      177,  178,  178,  178,  178,  178,  178,  179,    0,    0,
        0,    0,    0,  179,    0,    0,    0,  179,  180,    0,
        0,    0,    0,    0,  180,    0,    0,    0,  180,  181,
        0,    0,    0,    0,    0,  181,    0,    0,    0,  181,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,

      170,  170,  170,  170,  170,  170,  170,  170
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "read.lex"
/* -*- c-syntactic-indentation: nil; electric-indent-inhibit: t -*- */
/* The reader, uses flex

Copyright (C) 2014 Tucker DiNapoli
This file is part of SciLisp.

SciLisp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

SciLisp is distributed in the hope that it will be useful,
35but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with SciLisp.  If not, see <http://www.gnu.org*/
#line 20 "read.lex"
/*****************************************************************
 * Copyright (C) 2013 Tucker DiNapoli                            *
 * SciLisp is Licensed under the GNU General Public License V3   *
 ****************************************************************/
#define IN_LEXER
#include "common.h"
/*#include "prim.h"*/
#include "unicode.h"
#include "read.h"
#include "cons.h"
#ifdef YY_DECL
#undef YY_DECL
#endif
#define YY_DECL TOKEN yylex(sexp *yylval,yyscan_t yyscanner)
#define YYSTYPE sexp
static int comment_depth=0;
static thread_local int backtick_flag=0;
#define FORMAT_READ_ERR(format,args...)       \
  ({CORD read_err_string;                     \
    CORD_sprintf(&read_err_string,            \
    format,##args);                           \
    read_err_string;})
/*FLEX COMMENT RULES:
Comment needs to start after a space on a line;
Comments can't be on the same line as a defination
Need to use / * * / comments  */
/*backslashes and quotes are refered to using ascii escapes
\x5c == \ & \x22 == " & \x27 == '
mostly so unmatched quotes don't fuck up syntax highlighing*/
/*Unicode support, basic idea borrowed from the lexer for
*the txr by kaz kylheku language*/
/*explaination of special characters:
* : reserved for keywords, pacakge access and type annotations
* ; reserved for comments
* (){}[] reserved delimiers, () should be obvious, [] for arrays and {} for future use
* ' " ' quotes, obviously
* # for quoting and delimiting special symbols(#t,#f) and deliberately unreaable symbols
* . reserved for pairs and package access
* | nothing now but reserved for later (quoting ids?)
* @ for ,@ in macros
* , for macros
* Starting special characters ? for characters, +-[0-9] for numbers
*/
/*                                  '   "    [  \   ]        space*/
/*start condition for scanning nested comments*/

#line 777 "read.c"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

int yyget_column  (yyscan_t yyscanner );

void yyset_column (int column_no ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 94 "read.lex"

 /*numbers need to come first so something like +1 gets read as an integer
  but something like 1+ gets read as a symbol*/
#line 1007 "read.c"

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 171 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 961 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 97 "read.lex"
{LEX_MSG("lexing int");
  *yylval=long_sexp((long)strtol(yytext,NULL,0));return TOK_INT;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 99 "read.lex"
{LEX_MSG("lexing hex int");
  *yylval=long_sexp((long)strtol(yytext,NULL,0));return TOK_INT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 101 "read.lex"
{LEX_MSG("lexing real");
  *yylval=real64_sexp(strtod(yytext,NULL));return TOK_REAL;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 103 "read.lex"
{LEX_MSG("lexing real");
  *yylval=real64_sexp(strtod(yytext,NULL));return TOK_REAL;}
	YY_BREAK
/*String Literal a quote, followed by either a literal \"
   or anything that isnt a " repeated 1 or more times, followed by another quote.*/
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 107 "read.lex"
{LEX_MSG("Lexing string");
  *yylval=cord_sexp(CORD_strdup(CORD_substr(yytext,1,CORD_len(yytext)-2)));
  return TOK_STRING;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 110 "read.lex"
{LEX_MSG("Lexing multibyte string");
  *yylval=cord_sexp(CORD_strdup(CORD_substr(yytext,1,CORD_len(yytext)-2)));
  return TOK_STRING;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 113 "read.lex"
{*yylval=cord_sexp(0);return TOK_STRING;}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 114 "read.lex"
{LEX_MSG("lexing char");
    wint_t new_char;
    if(lex_char(yytext+1,&new_char)<0){
      return TOK_UNKN;
    } else {
      *yylval=uchar_sexp(new_char); return TOK_CHAR;
    }
  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 122 "read.lex"
{LEX_MSG("lexing symbol");
    symbol *sym=c_intern(yytext,yyleng,NULL);
    *yylval=symref_sexp(sym);
    return TOK_SYMBOL;
   }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 127 "read.lex"
{LEX_MSG("lexing keyword symbol");CORD name=CORD_from_char_star(yytext);
   symbol *sym=c_intern(yytext,yyleng,NULL);
   *yylval=symref_sexp(sym);
    return TOK_KEYSYM;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 131 "read.lex"
{LEX_MSG("lexing qualified id");
  /*know we've got a colon, so we can use rawmemchr*/
  char *colon=rawmemchr(yytext,':');
  symbol *package=c_intern(yytext,(uint32_t)(colon-yytext),NULL);
  if(!ENVP(package->val)){
    /*yylval=format_error_sexp("unknown package %s",package->name.name);*/
    return TOK_ERR;
  }
  symbol_name *sym_name=make_symbol_name(colon+1,(uint32_t)((yytext+yyleng)-(colon+1)),0);
  symbol *sym=obarray_lookup_sym(sym_name,package->val.val.ob);
  if(!sym){
    raise_simple_error(Eundefined,FORMAT_READ_ERR
      ("value %s not found in package %s",sym_name->name,package->name->name));
  }
  if(sym->visibility == 2){
    /*use Evisibility once I define it*/
    raise_simple_error(Eundefined,FORMAT_READ_ERR
    ("value %s not externally visable in package %s (use :. to override visibility)",
      sym_name->name,package->name->name));
   }
   *yylval=symref_sexp(sym);
   return TOK_ID;
   }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 154 "read.lex"
{LEX_MSG("lexing qualified id");
  /*know we've got a colon, so we can use rawmemchr*/
  char *colon=rawmemchr(yytext,':');
  assert(*(colon+1) == '.');
  symbol *package=c_intern(yytext,(uint32_t)(colon-yytext),0);
  if(!ENVP(package->val)){
    raise_simple_error(Eundefined,
    FORMAT_READ_ERR("unknown package %s",package->name->name));
  }
  symbol_name *sym_name=make_symbol_name(
    colon+2,(uint32_t)((yytext+yyleng)-(colon+2)),0);
  symbol *sym=obarray_lookup_sym(sym_name,package->val.val.ob);
  if(!sym){
    raise_simple_error(Eundefined,FORMAT_READ_ERR("value %s not found in package %s",
      sym_name->name,package->name->name));
  }
  *yylval=symref_sexp(sym);
  return TOK_ID;
  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 173 "read.lex"
{LEX_MSG("lexing typename");
  symbol *type_sym=lookup_symbol_global(yytext+2);
  if(!TYPEP(type_sym->val)){
    raise_simple_error_fmt(Etype,"Unknown type %s",yytext+2);
  }
  *yylval=type_sym->val;
  return TOK_TYPEINFO;
  }
	YY_BREAK
/*
{ID}{TYPENAME} {LEX_MSG("lexing typed id");
    char *colon=rawmemchr(yytext,':');
    assert(*(colon+1) == ':');
    symbol sym=c_intern(yytext,(uint32_t)(colon-yytext),NULL);
    }
    */
case 14:
YY_RULE_SETUP
#line 188 "read.lex"
{LEX_MSG("lexing open comment");
  if(YY_START != comment){BEGIN(comment);}comment_depth+=1;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 190 "read.lex"
{LEX_MSG("lexing close comment"); comment_depth-=1;
  if(comment_depth == 0){BEGIN(0);}}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 192 "read.lex"

	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 193 "read.lex"

	YY_BREAK
case 18:
YY_RULE_SETUP
#line 194 "read.lex"
{LEX_MSG("lexing backquote");return TOK_BACKQUOTE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 195 "read.lex"
{LEX_MSG("HASH");return TOK_HASH;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 196 "read.lex"
{*yylval=LISP_TRUE; return TOK_SYMBOL;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 197 "read.lex"
{*yylval=LISP_FALSE; return TOK_SYMBOL;}
	YY_BREAK
/*uninterned symbol*/
case 22:
YY_RULE_SETUP
#line 199 "read.lex"
{struct symbol_name *name=make_symbol_name(yytext+2,yyleng-2,0);
          symbol *sym=xmalloc(sizeof(struct symbol));
          sym->name=name;
          sym->val=UNBOUND; /*define this at some point*/
          sym->next=NULL;
          sym->plist=Fcons(Tuninterned_sexp,NIL);
          *yylval=symref_sexp(sym);
          return TOK_SYMBOL;
         }
	YY_BREAK
/*"#"{ID} {LEX_MSG("HASH-ID");return TOK_HASH;}*/
case 23:
YY_RULE_SETUP
#line 209 "read.lex"
{LEX_MSG("lexing (");return TOK_LPAREN;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 210 "read.lex"
{LEX_MSG("lexing )");return TOK_RPAREN;}
	YY_BREAK
/*Maybe use the syntax #('['|'[['|'[|') for something*/
case 25:
YY_RULE_SETUP
#line 212 "read.lex"
{LEX_MSG("lexing [");return TOK_LBRACE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 213 "read.lex"
{LEX_MSG("lexing ");return TOK_DBL_LBRACE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 214 "read.lex"
{LEX_MSG("lexing [|");return TOK_MAT_OPEN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 215 "read.lex"
{LEX_MSG("lexing ]");return TOK_RBRACE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 216 "read.lex"
{LEX_MSG("lexing ");return TOK_DBL_RBRACE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 217 "read.lex"
{LEX_MSG("lexing |]");return TOK_MAT_CLOSE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 218 "read.lex"
{LEX_MSG("lexing {");return TOK_LCBRACE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 219 "read.lex"
{LEX_MSG("lexing }");return TOK_RCBRACE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 220 "read.lex"
{LEX_MSG("lexing .");return TOK_DOT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 221 "read.lex"
{LEX_MSG("lexing :");return TOK_COLON;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 222 "read.lex"
{LEX_MSG("lexing @");return TOK_STRUDEL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 223 "read.lex"
{LEX_MSG("Lexing quote");return TOK_QUOTE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 224 "read.lex"
{LEX_MSG("Lexing comma");return TOK_COMMA;}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 225 "read.lex"
/*whitespace*/
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 226 "read.lex"
/*one line comments*/
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
#line 227 "read.lex"
return -1;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 228 "read.lex"
{LEX_MSG("unknown token");
  PRINT_FMT("Error, unknown token, value %d, character %c",
            yytext[0],yytext[0]);
  *yylval=uchar_sexp(btowc(yytext[0]));
  return TOK_UNKN;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 234 "read.lex"
ECHO;
	YY_BREAK
#line 1401 "read.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 171 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 171 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 170);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#line 234 "read.lex"


#include "lex_read.c"

